# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'Panorama360_MatterportAxis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Panorama360_MatterportAxis
  pod 'SwiftFormat/CLI', :configurations => ['Debug']

end
