name: Build & Publish Release APK

on:
  push:
    tags:
      - 'android_v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/Panorama360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17.0.10
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run
        run: |
          pwd
          ls
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ./keystore.jks
      - name: Build With Gradle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes ${{ github.ref_name }} ./app/build/outputs/apk/release/app-release.apk
